/* Personal Gmail collector. Configure Script Properties: INGEST_URL, COLLECTOR_TOKEN,
 * BACKFILL_SINCE (default 2026-07-24), and optional BACKFILL_BATCH_SIZE. Never commit tokens. */
const TYPES = ['deadline','selection_event','test','interview','application_open','result_notice','reservation_required','manual_mypage_check_required','attachment_review_required','general_recruiting_information','eligibility_review_required','unknown'];
function runInitialBackfill() { return runCollector_(true); }
function runDailyIncremental() { return runCollector_(false); }
function runCollector_(backfill) {
  const p = PropertiesService.getScriptProperties(); const now = new Date(); const since = backfill ? new Date(p.getProperty('BACKFILL_SINCE') || '2026-07-24T00:00:00+09:00') : new Date(p.getProperty('LAST_SUCCESSFUL_SYNC') || p.getProperty('BACKFILL_SINCE') || '2026-07-24T00:00:00+09:00');
  since.setHours(since.getHours() - 2); const query = `after:${Utilities.formatDate(since, 'Asia/Tokyo', 'yyyy/MM/dd')} (採用 OR 選考 OR 面接 OR ES OR "Webテスト" OR 適性検査 OR エントリー OR インターン OR 説明会 OR 結果 OR 締切 OR マイページ)`;
  const pageToken = p.getProperty('RESUME_PAGE_TOKEN') || undefined; const batch = Number(p.getProperty('BACKFILL_BATCH_SIZE') || '50'); const list = Gmail.Users.Messages.list('me', { q: query, maxResults: batch, pageToken }); const findings = (list.messages || []).map(ref => toFinding_(Gmail.Users.Messages.get('me', ref.id, { format: 'full' }), now));
  ingest_(findings); if (list.nextPageToken) { p.setProperty('RESUME_PAGE_TOKEN', list.nextPageToken); return; } p.deleteProperty('RESUME_PAGE_TOKEN'); p.setProperty('LAST_SUCCESSFUL_SYNC', now.toISOString());
}
function classify_(text, attachment) { if (attachment) return 'attachment_review_required'; if (/(エントリー|応募).{0,12}(受付|受け付け|ありがとう|完了)/.test(text)) return 'entry_completed'; if (/マイページ.{0,30}(確認|ご覧)/.test(text)) return 'manual_mypage_check_required'; if (/締切|までに提出/.test(text)) return 'deadline'; if (/面接/.test(text)) return 'interview'; if (/テスト|適性検査/.test(text)) return 'test'; if (/結果/.test(text)) return 'result_notice'; return 'unknown'; }
function extractDeadline_(text, now) { const match = text.match(/(?:20(\\d{2})[年\\/.-])?\\s*(\\d{1,2})[月\\/.-](\\d{1,2})日?(?:[^0-9]{0,12}(\\d{1,2}):(\\d{2}))?/); if (!match) return null; const year = match[1] ? 2000 + Number(match[1]) : now.getFullYear(); const value = new Date(year, Number(match[2]) - 1, Number(match[3]), Number(match[4] || 23), Number(match[5] || 59), 0); return Number.isFinite(value.getTime()) ? value.toISOString() : null; }
function toFinding_(message, now) { const headers = Object.fromEntries((message.payload.headers || []).map(h => [h.name.toLowerCase(), h.value])); const text = extractText_(message.payload); const subject = headers.subject || ''; const attachment = hasAttachment_(message.payload); const all = subject + '\n' + text; const type = classify_(all, attachment); const deadline = type === 'deadline' ? extractDeadline_(all, now) : null; return { finding_type: type, source_external_id: message.id, source_timestamp: new Date(Number(message.internalDate)).toISOString(), observed_at: now.toISOString(), company: null, confidence: 0.4, evidence_excerpt: subject.slice(0, 300), payload: { subject, sender: headers.from || '', attachment, deadline, urls: (text.match(/https?:\/\/[^\s<>]+/g) || []).slice(0, 5) }, fingerprint: `gmail:${message.id}:${type}` }; }
function extractText_(part) { const own = part.body && part.body.data ? Utilities.newBlob(Utilities.base64DecodeWebSafe(part.body.data)).getDataAsString('UTF-8') : ''; return [own].concat((part.parts || []).map(extractText_)).join('\n').replace(/<script[\s\S]*?<\/script>/gi, '').replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').slice(0, 2000); }
function hasAttachment_(part) { return Boolean(part.filename || (part.parts || []).some(hasAttachment_)); }
function ingest_(findings) { const p = PropertiesService.getScriptProperties(); const response = UrlFetchApp.fetch(p.getProperty('INGEST_URL'), { method: 'post', contentType: 'application/json', headers: { Authorization: 'Bearer ' + p.getProperty('COLLECTOR_TOKEN'), 'x-collector-type': 'gmail' }, payload: JSON.stringify({ findings }), muteHttpExceptions: true }); if (response.getResponseCode() >= 300) throw new Error('ingest failed: ' + response.getResponseCode()); }
